GRANT SELECT, INSERT, UPDATE, DELETE ON Portal_User TO cdh8zs_a;
GRANT SELECT, INSERT, UPDATE, DELETE ON Player TO cdh8zs_a;
GRANT SELECT, INSERT, UPDATE, DELETE ON Running_Back TO cdh8zs_a;
GRANT SELECT, INSERT, UPDATE, DELETE ON Quarterback TO cdh8zs_a;
GRANT SELECT, INSERT, UPDATE, DELETE ON Wide_Receiver TO cdh8zs_a;
GRANT SELECT, INSERT, UPDATE, DELETE ON Linebacker TO cdh8zs_a;
GRANT SELECT, INSERT, UPDATE, DELETE ON Safety TO cdh8zs_a;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kicker TO cdh8zs_a;
GRANT SELECT, INSERT, UPDATE, DELETE ON Offers TO cdh8zs_a;
GRANT SELECT, INSERT, UPDATE, DELETE ON Plays_For TO cdh8zs_a;
GRANT SELECT, INSERT, UPDATE, DELETE ON Plays_As TO cdh8zs_a;

GRANT SELECT ON Coach TO cdh8zs_a;
GRANT SELECT ON Team TO cdh8zs_a;